name: CI
on:
  pull_request:
  push:
    branches: [ master ]   

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Project Files  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - name: Build & Test
        run: mvn -B clean verify
      - run: mvn -Pspotbugs -B verify
      - env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}

